<?php

/**
 * @file
 * Contains ics_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_help().
 */
function ics_field_help($routeName,
                                   RouteMatchInterface $routeMatch) {
  switch ($routeName) {
    // Main module help for the ics_field module.
    case 'help.page.ics_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' .
                 t('A module providing a calendar download as an .ics file') .
                 '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave().
 */
function ics_field_entity_presave(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface && $entity->getEntityTypeId() == 'node') {
    $icsFileManager = \Drupal::service('ics_field.file_manager');
    $icsFileManager->updateFileField($entity);
  }
}
